-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKUCOzwyqqfLub29j
hXTPsi2LRlIsxSmbKVm+ssgmXMKgCgYIKoZIzj0DAQehRANCAATHvGdeEGo+62a2
YHmxqVBCoVP7Bc45XJ+oKgx+xsLJJD90LqWY0XjJLYrNQnE5kwg2L09sn2LccvZ6
2hQ8l/+Y
-----END PRIVATE KEY-----